name: Build Flutter APK build-1782458171971

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 'stable'
          
      - name: Download Project
        run: |
          wget -O project.zip "https://github.com/ObyMoods/webApk/releases/download/build-1782458171971/project.zip"
          unzip -o project.zip -d .
          rm project.zip
          
      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
    